// Project data.
window.HAMLAYA_PROJECTS = [
  {
    id: 'kingdom-reforged',
    title: 'Kingdom Reforged',
    year: '2025',
    status: 'Editor',
    tagline: 'A kingdom built one rule at a time.',
    description: 'World and rules editor for the Kingdom universe — build, balance, and share scenarios.',
    tech: ['Web', 'Editor'],
    role: 'Solo developer',
    pos: [-2.4, 1.0, 0.3],
    color: '#d8c36a',
    size: 1.2,
    link: 'https://kingdom.hamlaya.com',
  },
  {
    id: 'kingdom-expeditions',
    title: 'Kingdom Expeditions',
    year: '2025',
    status: 'Prototype',
    tagline: 'Send your party past the edge of the map.',
    description: 'Expedition-based gameplay layered on the Kingdom universe — exploration, encounters, returns.',
    tech: ['Web', 'Game'],
    role: 'Solo developer',
    pos: [2.4, 1.0, -0.3],
    color: '#c7eee7',
    size: 1.15,
    link: 'https://exp.hamlaya.com',
  },
  {
    id: 'train-builder',
    title: 'Train Builder',
    year: '2025',
    status: 'In development',
    tagline: 'Lay the track, run the line, watch it grow.',
    description: 'A relaxed building game about composing rail networks across procedural terrain.',
    tech: ['Web', 'Game'],
    role: 'Solo developer',
    pos: [2.8, -0.6, 0.2],
    color: '#c89460',
    size: 1.1,
    link: 'https://train.hamlaya.com',
  },
  {
    id: 'crush-candy',
    title: 'Crush Candy',
    year: '2024',
    status: 'Released',
    tagline: 'Three in a row, sweetly.',
    description: 'A bright match-three in the Candy Crush vein — quick rounds, sharp animation, no nonsense.',
    tech: ['Web', 'Game'],
    role: 'Solo developer',
    pos: [0.0, -1.6, 0.5],
    color: '#e88a98',
    size: 1.05,
    link: 'https://crush.hamlaya.com',
  },
  {
    id: 'loop',
    title: 'Loop',
    year: '2025',
    status: 'Prototype',
    tagline: 'A puzzle that closes back on itself.',
    description: 'A small puzzle game about circular causality — every action eventually returns to you.',
    tech: ['Web', 'Puzzle'],
    role: 'Solo developer',
    pos: [-2.8, -0.6, 0.2],
    color: '#a8b0d4',
    size: 1.0,
    link: 'https://loop.hamlaya.com',
  },
];
