// Project data — placeholders. Replace with your actual projects.
window.HAMLAYA_PROJECTS = [
  {
    id: 'ghostlight',
    title: 'Ghostlight',
    year: '2025',
    status: 'In development',
    tagline: 'A lantern. A mountain. Something following.',
    description: 'A first-person exploration game set in a fog-bound alpine valley. Light the way, decode the markers, and discover what walked these paths before you.',
    tech: ['Unity', 'HDRP', 'C#'],
    role: 'Solo developer',
    pos: [-2.2, 0.9, 0.4],
    color: '#e2b86c',
    size: 1.3,
    link: 'https://hamlaya.studio/ghostlight',
  },
  {
    id: 'cartographer',
    title: 'The Cartographer\u2019s Daughter',
    year: '2024',
    status: 'Released',
    tagline: 'Map the world your father left unfinished.',
    description: 'A narrative adventure about grief, geography, and the slow craft of mapmaking. Hand-drawn 2D, branching prose, ambient score.',
    tech: ['Godot', 'GDScript', 'Ink'],
    role: 'Design & writing',
    pos: [1.7, 1.4, -0.6],
    color: '#b8c6dc',
    size: 1.1,
    link: 'https://hamlaya.studio/cartographers-daughter',
  },
  {
    id: 'tidefall',
    title: 'Tidefall',
    year: '2025',
    status: 'Prototype',
    tagline: 'A roguelike about the things that wash ashore.',
    description: 'Turn-based roguelike with tide mechanics \u2014 each run, the sea reshapes the island. Inventory is whatever the waves bring.',
    tech: ['TypeScript', 'PixiJS', 'Web'],
    role: 'Prototype lead',
    pos: [-0.4, -0.6, 0.8],
    color: '#7fb6c7',
    size: 1.0,
    link: 'https://hamlaya.studio/tidefall',
  },
  {
    id: 'solanin',
    title: 'Solanin',
    year: '2026',
    status: 'In development',
    tagline: 'Two friends. One shared dream.',
    description: 'Asymmetric co-op set inside a recurring dream. One player plays the dreamer, the other plays the dream. Online or split-screen.',
    tech: ['Unreal 5', 'Blueprints', 'C++'],
    role: 'Tech & multiplayer',
    pos: [2.4, -0.4, 0.2],
    color: '#c89dd4',
    size: 1.15,
    link: 'https://hamlaya.studio/solanin',
  },
  {
    id: 'mossroot',
    title: 'Mossroot',
    year: '2025',
    status: 'Concept',
    tagline: 'A garden, a kettle, and the slow turn of the year.',
    description: 'Cozy simulation where you tend a forest garden across four seasons. No combat, no failure \u2014 just attention, patience, and growing things.',
    tech: ['Godot', 'GDScript'],
    role: 'Solo developer',
    pos: [-1.6, -1.2, -0.4],
    color: '#9ec19a',
    size: 0.95,
    link: 'https://hamlaya.studio/mossroot',
  },
  {
    id: 'ferryman',
    title: 'Ferryman',
    year: '2023',
    status: 'Released',
    tagline: 'A short story about a debt and a river.',
    description: 'A 90-minute narrative game. Read the manifests, listen to the passengers, decide who crosses. Won the SmallTales narrative prize, 2023.',
    tech: ['Twine', 'CSS'],
    role: 'Writer / Designer',
    pos: [0.6, 1.8, -1.0],
    color: '#e8d4a0',
    size: 0.9,
    link: 'https://hamlaya.studio/ferryman',
  },
];
